# baseURL = 'https://exiledcapacities.com/'
baseURL = 'https://temp-rec.netlify.app/'
languageCode = 'en-us'
title = 'Reactivating Exiled Capacities'
theme = 'capacities-theme'

# Site parameters
[params]
  description = "Stories of rediscovering lost abilities and talents"
  author = "Exiled Capacities Team"

# UPDATED Menu configuration - Stories changed to Mapping Capacities
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Mapping Capacities"
    url = "/mapping-capacities/"
    weight = 30

# Content configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Output formats for JSON data (needed for clusters visualization)
[outputs]
  home = ["HTML", "JSON"]

# Disable taxonomies for now (fixes the warnings)
disableKinds = ["taxonomy", "term"]

# Alternative: Enable specific taxonomies if you want them later
# [taxonomies]
#   tag = "tags"
#   category = "categories"