baseURL = 'https://temp-rec.netlify.app'
languageCode = 'en-us'
title = 'Reactivating Exiled Capacities'
theme = 'capacities-theme'

# Enable HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    
      unsafe = true

# Site parameters
[params]
  description = "Rediscovering forgotten human abilities and talents through an interconnected, network-based approach"

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "Mapping Capacities"
  url = "/mapping-capacities/"
  weight = 30

# Output formats for JSON data
[outputs]
  home = ["HTML", "JSON"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "clusters"
    isPlainText = true

# Disable unused content types
disableKinds = ["taxonomy", "term"]