baseURL = 'https://temp-rec.netlify.app'
languageCode = 'en-us'
title = 'reactivating exiled capacities'

# Remove theme since we're using custom layouts
# theme = 'capacities-theme'

# Enable HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site parameters
[params]
  description = ""
  # Optional: Add Open Graph image for social sharing
  ogImage = "/images/og-mycelium.jpg"
  # Background image for splash page - using your existing image
  backgroundImage = "/images/soil-background.jpg"

# Menu configuration for internal navigation
[[menu.main]]
  name = "home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "about the inquiry"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "the nervous system as relational fabric"
  url = "/nervous-system/"
  weight = 30

[[menu.main]]
  name = "mapping exiled capacities"
  url = "/mapping-capacities/"
  weight = 40

[[menu.main]]
  name = "artist residency 2024"
  url = "/residency/"
  weight = 50

[[menu.main]]
  name = "contact"
  url = "/contact/"
  weight = 60

# Disable unused content types - this should fix taxonomy warnings
disableKinds = ["taxonomy", "term", "RSS"]

# Output formats for JSON data
[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "clusters"
    isPlainText = true

# Build configuration
[build]
  writeStats = true

# Security settings
[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

# Privacy settings for GDPR compliance
[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.youtube]
    privacyEnhanced = true