# static/admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "clusters"
    label: "Clusters"
    folder: "content/clusters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Why This Cluster Matters", name: "why_matters", widget: "markdown" }
      - { label: "Cluster Image", name: "image", widget: "image", required: false }
      - { label: "Position X", name: "position_x", widget: "number", default: 0, value_type: "float" }
      - { label: "Position Y", name: "position_y", widget: "number", default: 0, value_type: "float" }
      - label: "Capacities"
        name: "capacities"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "What it is", name: "what_it_is", widget: "markdown" }
          - { label: "Why it's been exiled", name: "why_exiled", widget: "markdown" }
          - { label: "What it makes possible", name: "what_possible", widget: "markdown" }
          - label: "Distortions"
            name: "distortions"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - { label: "Node Color", name: "color", widget: "string", default: "#7c3aed" }
          - { label: "Position X", name: "position_x", widget: "number", default: 0, value_type: "float" }
          - { label: "Position Y", name: "position_y", widget: "number", default: 0, value_type: "float" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }